export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";

export const GET_MEDICINES = 'GET_MEDICINES';
export const POST_MEDICINES = 'POST_MEDICINES';
export const DELETE_MEDICINE = 'DELETE_MEDICINE';
export const UPDATE_MEDICINE = 'UPDATE_MEDICINE';
export const LOADING_MEDICINE = 'LOADING_MEDICINE';
export const ERROR_MEDICINE = 'ERROR_MEDICINE';

export const GET_FACILITIES = 'GET_FACILITIES';
export const POST_FACILITIES = 'POST_FACILITIES';
export const DELETE_FACILITY = 'DELETE_FACILITY';
export const UPDATE_FACILITY = 'UPDATE_FACILITY';
